#!/bin/sh

mkdir /var/log/nginx/
touch /var/log/nginx/access.log
mkdir -p /var/lib/nginx/tmp/client_body

cp -rf /usr/share/3dprinter-1.0/nginx_config/nginx.conf  /etc/nginx/
cp -rf /usr/share/3dprinter-1.0/nginx_config/sites-enabled  /etc/nginx/

nginx

/usr/bin/uwsgi -x /usr/share/3dprinter-1.0/app_config.xml -d /var/log/uwsgi.log
echo ""
echo "now you can connect to wifi"
echo "then you can acess x.x.x.x:88 to use 3dprinter."
